### ISSUE TITLE
无法安装melonloader

### ISSUE THREAD

**Issue by allan888** [MDModsDev/MuseDashModToolsUI#187]
### Operating system

Windows 10 and below

### Problem Detail (Optional)

用这个软件安装melonloader，进度条还未开始就提示无法解压melonder.zip，要求手动解压。但是下载的zip包是无效的，无法安装。

### Logs

[00:32:04.591 +08:00] [Information]
Available languages loaded: "en, de, es, fr, hr, hu, ja, ko, ru, zh-Hans, zh-Hant"
------------------------------

[00:32:04.694 +08:00] [Information]
Available fonts loaded: "等线,方正舒体,方正姚体,仿宋,黑体,华文彩云,华文仿宋,华文琥珀,华文楷体,华文隶书,华文宋体,华文细黑,华文新魏,华文行楷,华文中宋,楷体,隶书,青叶手写体,宋体,微软雅黑,新宋体,叶根友毛笔行书2.0版,幼圆,站酷快乐体2016修订版,站酷文艺体,Adobe 仿宋 Std,Adobe 黑体 Std,Adobe 楷体 Std,Adobe 宋体 Std,Adobe Arabic,Adobe Caslon Pro,Adobe Devanagari,Adobe Fan Heiti Std,Adobe Garamond Pro,Adobe Gothic Std,Adobe Hebrew,Adobe Ming Std,Adobe Myungjo Std,Adobe نسخ,Agency FB,Algerian,Arial,Arial Rounded MT,Arial Unicode MS,Bahnschrift,Baskerville Old Face,Bauhaus 93,Bell MT,Berlin Sans FB,Bernard MT,Birch Std,BIZ UDGothic,BIZ UDMincho,BIZ UDPGothic,BIZ UDPMincho,Blackadder ITC,Blackoak Std,Bodoni MT,Bodoni MT Poster,Book Antiqua,Bookman Old Style,Bookshelf Symbol 7,Bradley Hand ITC,Britannic,Broadway,Brush Script MT,Brush Script Std,Calibri,Californian FB,Calisto MT,Cambria,Cambria Math,Candara,Cascadia Code,Cascadia Mono,Castellar,Centaur,Century,Century Gothic,Century Schoolbook,Chaparral Pro,Charlemagne Std,Chiller,Colonna MT,Comic Sans MS,Consolas,Constantia,Cooper,Cooper Std,Copperplate Gothic,Corbel,Courier New,Curlz MT,DejaVu Sans Mono,DFKai-SB,Dubai,Ebrima,Edwardian Script ITC,Elephant,Engravers MT,Eras ITC,Felix Titling,Fira Code,Fira Code Retina,FiraCode Nerd Font,FiraCode Nerd Font Mono,FiraCode Nerd Font Propo,Footlight MT,Forte,Franklin Gothic,Franklin Gothic Book,Freestyle Script,French Script MT,Gabriola,Gadugi,Garamond,Georgia,Giddyup Std,Gigi,Gill Sans,Gill Sans MT,Gloucester MT,Goudy Old Style,Goudy Stout,Haettenschweiler,hakuyoxingshu7000,Harlow Solid,Harrington,High Tower Text,Hobo Std,HoloLens MDL2 Assets,Impact,Imprint MT Shadow,Informal Roman,Ink Free,Javanese Text,Jokerman,Juice ITC,Kozuka Gothic Pr6N,Kozuka Gothic Pro,Kozuka Mincho Pr6N,Kozuka Mincho Pro,Kristen ITC,Kunstler Script,Leelawadee,Leelawadee UI,Letter Gothic Std,Lithos Pro,Lucida Bright,Lucida Calligraphy,Lucida Console,Lucida Fax,Lucida Handwriting,Lucida Sans,Lucida Sans Typewriter,Lucida Sans Unicode,Magneto,Maiandra GD,Malgun Gothic,Marlett,Matura MT Script Capitals,Meiryo,Meiryo UI,Mesquite Std,Microsoft Himalaya,Microsoft JhengHei,Microsoft JhengHei UI,Microsoft New Tai Lue,Microsoft PhagsPa,Microsoft Sans Serif,Microsoft Tai Le,Microsoft Uighur,Microsoft YaHei UI,Microsoft Yi Baiti,MingLiU,MingLiU_HKSCS,MingLiU_HKSCS-ExtB,MingLiU-ExtB,Minion Pro,Mistral,Modern No. 20,Mongolian Baiti,Monotype Corsiva,MS Gothic,MS Mincho,MS Outlook,MS PGothic,MS PMincho,MS Reference Sans Serif,MS Reference Specialty,MS UI Gothic,MT Extra,MV Boli,Myanmar Text,Myriad Hebrew,Myriad Pro,Myriad عربي,Niagara Engraved,Niagara Solid,Nirmala UI,Noto Serif CJK TC,Nueva Std,OCR A,OCR A Std,Old English Text MT,Onyx,Orator Std,Palace Script MT,Palatino Linotype,Papyrus,Parchment,Perpetua,Perpetua Titling MT,Playbill,PMingLiU,PMingLiU-ExtB,Poor Richard,Poplar Std,Prestige Elite Std,Pristina,qweather-icons,Rage,Ravie,Rockwell,Rosewood Std,Script MT,Segoe MDL2 Assets,Segoe Print,Segoe Script,Segoe UI,Segoe UI Emoji,Segoe UI Historic,Segoe UI Symbol,Showcard Gothic,SimSun-ExtB,Sitka Banner,Sitka Display,Sitka Heading,Sitka Small,Sitka Subheading,Sitka Text,Snap ITC,Stencil,Stencil Std,Sylfaen,Symbol,Tahoma,Tekton Pro,Tempus Sans ITC,Times New Roman,Trajan Pro,Trebuchet MS,Tw Cen MT,UD Digi Kyokasho N-B,UD Digi Kyokasho N-R,UD Digi Kyokasho NK-B,UD Digi Kyokasho NK-R,UD Digi Kyokasho NP-B,UD Digi Kyokasho NP-R,Verdana,Viner Hand ITC,Vivaldi,VL Gothic,Vladimir Script,Webdings,Wide Latin,Wingdings,Wingdings 2,Wingdings 3,Yu Gothic,Yu Gothic UI,Yu Mincho"
------------------------------

[00:32:04.698 +08:00] [Information]
Saved setting loaded from Settings.json
------------------------------

[00:32:05.905 +08:00] [Information]
Switching tab to "ModManage"
------------------------------

[00:32:05.909 +08:00] [Information]
Checking updates...
------------------------------

[00:32:05.911 +08:00] [Information]
Get current version success: "1.3.0"
------------------------------

[00:32:05.977 +08:00] [Information]
Initializing settings...
------------------------------

[00:32:05.979 +08:00] [Information]
Detecting null settings...
------------------------------

[00:32:05.981 +08:00] [Information]
Checking valid path...
------------------------------

[00:32:05.983 +08:00] [Information]
Game files exists
------------------------------

[00:32:05.989 +08:00] [Information]
Correct game version "2019.4.32.16288752"
------------------------------

[00:32:05.993 +08:00] [Information]
Write path into cfg file successfully
------------------------------

[00:32:05.993 +08:00] [Information]
Path verified "D:\steam\steamapps\common\Muse Dash"
------------------------------

[00:32:06.000 +08:00] [Information]
Settings Window initialized
------------------------------

[00:32:06.004 +08:00] [Information]
Initializing mod list...
------------------------------

[00:32:06.339 +08:00] [Information]
Game version read successfully: "3.10.0"
------------------------------

[00:32:07.462 +08:00] [Information]
Main Window initialized
------------------------------

[00:32:07.893 +08:00] [Information]
Get releases success
------------------------------

[00:32:07.895 +08:00] [Information]
Get latest version success: "1.3.0"
------------------------------

[00:32:10.045 +08:00] [Information]
Showing MelonLoader download window...
------------------------------

[00:32:10.061 +08:00] [Information]
Start downloading MelonLoader
------------------------------

[00:32:10.607 +08:00] [Information]
Get MelonLoader Download ResponseHeader from "https://gitee.com/lxymahatma/ModLinks/raw/main/MelonLoader.zip" success
------------------------------

[00:32:10.612 +08:00] [Information]
Download MelonLoader.zip success
------------------------------

[00:32:10.616 +08:00] [Information]
Extracting MelonLoader.zip
------------------------------

[00:32:10.757 +08:00] [Error]
Extracting MelonLoader.zip failed
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream, Boolean leaveOpen, StringCodec stringCodec)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean allowParentTraversal)
   at MuseDashModToolsUI.ViewModels.Dialogs.DownloadWindowViewModel.ExtractMelonLoaderZipFile()
------------------------------

[00:32:13.600 +08:00] [Information]
Get mod list from "https://gitee.com/lxymahatma/ModLinks/raw/main/ModLinks.json" success
------------------------------

[00:32:13.621 +08:00] [Information]
Mod list deserialized
------------------------------

[00:32:13.641 +08:00] [Information]
Local mod "ChartReview" loaded. File name "ChartReview.dll"
------------------------------

[00:32:13.651 +08:00] [Information]
Local mod "Cinema" loaded. File name "Cinema.dll"
------------------------------

[00:32:13.673 +08:00] [Information]
Local mod "CustomAlbums" loaded. File name "CustomAlbums.dll"
------------------------------

[00:32:13.674 +08:00] [Information]
Local mod "Headquarters" loaded. File name "Headquarters.dll"
------------------------------

[00:32:13.688 +08:00] [Information]
Local mod "Muse Dash Mirror" loaded. File name "MuseDashMirror.dll"
------------------------------

[00:32:13.690 +08:00] [Information]
Local mod "MuseDashModTools" loaded. File name "MuseDashModTools.dll"
------------------------------

[00:32:13.690 +08:00] [Information]
Read all local mods info success
------------------------------

[00:32:13.748 +08:00] [Information]
Mod "ChartReview" loaded to UI
------------------------------

[00:32:13.748 +08:00] [Information]
Mod "Cinema" loaded to UI
------------------------------

[00:32:13.748 +08:00] [Information]
Mod "CustomAlbums" loaded to UI
------------------------------

[00:32:13.749 +08:00] [Information]
Mod "Headquarters" loaded to UI
------------------------------

[00:32:13.749 +08:00] [Information]
Mod "Muse Dash Mirror" loaded to UI
------------------------------

[00:32:13.749 +08:00] [Information]
Mod "MuseDashModTools" loaded to UI
------------------------------

[00:32:13.752 +08:00] [Information]
Mods Dll File Monitor Started
------------------------------

[00:32:13.752 +08:00] [Information]
Mod Manage Window Initialized
------------------------------

[00:33:07.555 +08:00] [Information]
Showing MelonLoader download window...
------------------------------

[00:33:08.231 +08:00] [Information]
Get MelonLoader Download ResponseHeader from "https://gitee.com/lxymahatma/ModLinks/raw/main/MelonLoader.zip" success
------------------------------

[00:33:08.232 +08:00] [Information]
Extracting MelonLoader.zip
------------------------------

[00:33:08.356 +08:00] [Error]
Extracting MelonLoader.zip failed
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream, Boolean leaveOpen, StringCodec stringCodec)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(String zipFileName, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean allowParentTraversal)
   at MuseDashModToolsUI.ViewModels.Dialogs.DownloadWindowViewModel.ExtractMelonLoaderZipFile()
------------------------------

[00:33:18.624 +08:00] [Error]
MelonLoader folder not found, showing error message box...
------------------------------

[00:33:21.938 +08:00] [Information]
Switching tab to "Setting"
------------------------------

[00:33:23.137 +08:00] [Information]
Choose path button clicked
------------------------------

[00:33:23.138 +08:00] [Information]
Showing choose folder dialogue
------------------------------

[00:33:33.172 +08:00] [Information]
User chose path "D:\steam\steamapps\common\Muse Dash"
------------------------------

[00:33:33.172 +08:00] [Information]
Detecting null settings...
------------------------------

[00:33:33.172 +08:00] [Information]
Checking valid path...
------------------------------

[00:33:33.172 +08:00] [Information]
Game files exists
------------------------------

[00:33:33.173 +08:00] [Information]
Correct game version "2019.4.32.16288752"
------------------------------

[00:33:33.179 +08:00] [Information]
Write path into cfg file successfully
------------------------------

[00:33:33.179 +08:00] [Information]
Path verified "D:\steam\steamapps\common\Muse Dash"
------------------------------

[00:33:33.180 +08:00] [Information]
Initializing mod list...
------------------------------

[00:33:33.304 +08:00] [Information]
Game version read successfully: "3.10.0"
------------------------------

[00:33:35.607 +08:00] [Information]
Showing MelonLoader download window...
------------------------------

[00:33:35.903 +08:00] [Fatal]
Unhandled exception
System.InvalidOperationException: No loaded DialogHost instances.
   at DialogHostAvalonia.DialogHost.GetInstance(String dialogIdentifier)
   at DialogHostAvalonia.DialogHost.Show(Object content, String dialogIdentifier, DialogOpenedEventHandler openedEventHandler, DialogClosingEventHandler closingEventHandler)
   at DialogHostAvalonia.DialogHost.Show(Object content, String dialogIdentifier, DialogOpenedEventHandler openedEventHandler)
   at MuseDashModToolsUI.Services.LocalService.OnInstallMelonLoader()
   at MuseDashModToolsUI.Services.LocalService.CheckMelonLoaderInstall()
   at MuseDashModToolsUI.Services.ModService.InitializeModList(SourceCache`2 sourceCache, ReadOnlyObservableCollection`1 mods)
   at MuseDashModToolsUI.ViewModels.Tabs.ModManageViewModel.Initialize()
   at MuseDashModToolsUI.Services.UpdateUIService.InitializeTabsOnChoosePath()
   at MuseDashModToolsUI.ViewModels.Tabs.SettingsViewModel.OnChoosePath()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at MuseDashModToolsUI.Program.Main(String[] args)
------------------------------

[00:33:36.473 +08:00] [Information]
Settings saved to Settings.json
------------------------------

**Comment by lxymahatma** [comment]
删除zip之后重新下载呢，还是一样的情况吗

**Comment by smallwhitedesu1** [comment]
> 删除zip之后重新下载呢，还是一样的情况吗

还是一样...

**Comment by lxymahatma** [comment]
> > 删除zip之后重新下载呢，还是一样的情况吗
> 
> 还是一样...

如果切换下载源还是不行的话那就去 https://github.com/MDModsDev/ModLinks/tree/main 手动下那个zip文件然后解压吧
