### ISSUE TITLE
[Bug]: App crashes when toggling the mod state

### ISSUE THREAD

**Issue by WiIIiamWei** [MDModsDev/MuseDashModToolsUI#232]
### I'm using the latest build release of Muse Dash Mod Tools and this problem still exists.

- [X] Yes

### There are no similar issues on the issue list

- [X] Yes

### Operating system

Windows 11

### Bug Detail

Pretty self-explainatory. Happens on all mods.

### Logs

A total of 21 logs were generated during this process. The Fatal error message looks the same, so I shall just give you this part. Everything else seems completely normal.
```
Unhandled exception
System.IO.FileNotFoundException: Error reading the  directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at MuseDashModToolsUI.ViewModels.Tabs.ModManageViewModel.ExecuteWithWatcherDisabled(Func`2 func, Mod item)
   at MuseDashModToolsUI.ViewModels.Tabs.ModManageViewModel.OnToggleMod(Mod item)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at MuseDashModToolsUI.Program.Main(String[] args)
```

**Comment by WiIIiamWei** [comment]
Well I think I'm also to blame for this. I just cloned everything from `https://github.com/MDModsDev/ModLinks/tree/main/Mods` and put it in the `Mods` folder, thinking the Mod Tool could manage them easily.

**Comment by lxymahatma** [comment]
yeah i think the new push in modlinks should fix the problem
